appveyor/website

NJekyll/site/docs/branches.md

The APPVEYOR_REPO_BRANCH contains the branch being built, not the tag name.

The actual tag name is not in the branch env var

---

NJekyll/site/docs/running-tests.md

<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/kimsk">@kimsk</a> it should be <a href="http://t.co/MIGbvKiSrp">http://t.co/MIGbvKiSrp</a> - will fix that shortly.</p>&mdash; AppVeyor CI (@appveyor) <a href="https://twitter.com/appveyor/status/542423598657310721">December 9, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Fix the build worker api link

---

NJekyll/site/docs/lang/nodejs-iojs.md

When you run the config through the validator as-is you get the error
> "environment" section must be a mapping. (Line: 3, Column: 3)

Fix config

---

NJekyll/site/docs/notifications.md

This makes the Webhook example consistent with the one embedded in the [appveyor-yml reference](http://www.appveyor.com/docs/appveyor-yml) page.

Extend the Webhook example slightly

---

NJekyll/site/docs/build-cache.md

As explained in https://help.appveyor.com/discussions/problems/2869-appdata-causes-error-parsing-appveyoryml-while-scanning-for-the-next-token-find-character-that-cannot-start-any-token#comment_37732584

Use single quote for %AppData%

---

NJekyll/site/docs/nuget.md

http://docs.nuget.org/release-notes/nuget-3.2-rc
https://github.com/NuGet/Home/issues/1186
Due to issue 1186 which is fixed in 3.2-rc if nuget failed to restore a package it did not provide the correct error code. Alternatively if the build VMs could be updated to use 3.2 that would be even better.

Get nuget v3.2.0-rc to get fix of issue 1186

---

NJekyll/site/docs/deployment/github.md

This fixes a bad certificate error when linking to `help.appveyor.com` as referenced in #90

remove https link to help.appveyor.com

---

NJekyll/site/docs/installed-software.md

Of course, it's obvious that Git is installed, but it's nice to know that Curl is available too.

Document Git and Curl in installed-software.md

---

NJekyll/site/docs/how-to/download-file.md

Since Curl is available on the build workers, this information would be useful for Unix users who may find Curl more familiar.

Mention the use of Curl in download-file.md

---

NJekyll/site/docs/installed-software.md

It seems the images have WiX 3.10, not 3.9.

Update WiX version to 3.10

---

NJekyll/site/docs/build-worker-api.md

Also changed the PUT for the first call to the api/artifacts endpoint to POST, since when I tried PUT it didn't work, but POST did!

Add details of how to upload artifacts to Google storage

---

NJekyll/site/docs/nuget.md

We had a lot of unstable restores in the past. We disabled Parallel Processing (also in more repositories), and we never had any problems (only when NuGet was really down). 
The change was made in sept 2015 and so far stable :)

Added NuGet Restore: Disable Parallel Processing

---

NJekyll/site/docs/nuget.md

Updating documentation to resolve https://github.com/appveyor/ci/issues/739

Add nuspec naming requirement into documentation

---

NJekyll/site/docs/services-databases.md

Replace ADO 'User ID' and 'Password' keywords with correct SQL Server Native Client ODBC and OLE DB UID and PWD.
-----
Currently presented connection string gives
```
[Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user ''.
[Microsoft][SQL Server Native Client 11.0]Invalid connection string attribute 
```
Reference [Using Connection String Keywords with SQL Server Native Client](https://msdn.microsoft.com/en-us/library/ms130822.aspx).

Fix SQL Server connection string

---

NJekyll/site/docs/deployment/nuget.md

Per the [support discussion](http://help.appveyor.com/discussions/questions/2299-how-to-put-the-appveyor-build-number-into-a-coappnuget-autopkg-file) I thought it might be useful to have this procedure explained in the documentation.

Add instructions for deploying NuGet packages with CoApp

---

NJekyll/site/docs/deployment/agent.md

FYI - changing the location of the deployment agent broke our production Chef recipes that deploy AppVeyor. Please consider advance notices to customers in the future if you change any endpoints.

Update path to agent

---

NJekyll/site/docs/branches.md

APPVEYOR_REPO_TAG seems to be  lower case.
I looked for the the mistake I made for half an hour, added the output for `true`:
https://ci.appveyor.com/project/AllYarnsAreBeautiful/knittingpattern/build/1.0.16#L1058
echo %APPVEYOR_REPO_TAG%
true
echo %APPVEYOR_REPO_TAG_NAME%
v0.1.7
IF %APPVEYOR_REPO_TAG% == True [...]
and for `false`: https://ci.appveyor.com/project/AllYarnsAreBeautiful/knittingpattern/build/1.0.17#L1047

Updated the capitalization of APPVEYOR_REPO_TAG

---

NJekyll/site/docs/environment-variables.md
NJekyll/site/docs/how-to/private-git-sub-modules.md
NJekyll/site/docs/how-to/repository-shallow-clone.md
NJekyll/site/docs/index.md
NJekyll/site/docs/nuget.md
NJekyll/site/docs/status-badges.md
NJekyll/site/terms-of-service.html

Replace "BitBucket" by "Bitbucket".
Reference: https://bitbucket.org/

Typo Bitbucket

---

NJekyll/site/docs/build-configuration.md

Expression `it's "queued" state longer than usual` seems not grammatically correct.

Update build-configuration.md - Grammar "it's"

---

NJekyll/site/docs/deployment/web-deploy.md

Use HTTPS instead of HTTP for https://technet.microsoft.com links.

Links to https://technet.microsoft.com - Use HTTPS

---

NJekyll/site/docs/installed-software.md

Documentation only mentions the installation prefix `C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0`, but it is unclear what is the actual structure of this.
Users either have to run `dir` during builds to discover or know details of MinGW-w64 distribution. This commit attempts to make it easier, for instance, to find which bin folder add to `PATH`.

Document bin folder location for MinGW-w64

---

src/docs/how-to/http-proxy.md

If the proxy port (APPVEYOR_HTTP_PROXY_PORT) is not set, the written configuration will be invalid and cause maven to fail trying to create a portnumber from a null

Check if proxy is set before writing maven proxy

---

src/docs/api/samples/download-artifacts-ps.md

The last get to download the file will fail if the Content-type header is present.
The proposed change will only add the authorization header to the last request.

The Powershell artifact download sample will fail with the Content-type set

---

src/docs/running-tests.md

Needed to avoid confusion with https://en.wikipedia.org/wiki/XUnit which is used by Python `nosetests` and perhaps other frameworks.

Rename xUnit to xUnit.net

---

src/docs/deployment/nuget.md

I had a very hard time finding the [AppVeyor Encryption Tool](https://ci.appveyor.com/tools/encrypt), since it seems to not be referenced from anywhere in the documentation. So when I found it, I added it here, because this is where I would have liked to have found it in the first place.

Added link to the AppVeyor Encryption Tool

---

src/docs/deployment/index.md

This is mutually exclusive as we have tag as branch name in webhook for tags

Remove branch condition from tag deployment

---

src/docs/build-worker-api.md

This shows a working PowerShell example to cast the Git date to a format that PowerShell's Get-Date can handle.

Add additional example for UpdateBuild

---

src/_posts/2016-11-22-create-signed-aligned-xamarin-apk.md
src/_posts/2016-12-23-sonarqube.md

Hi There
As discussed here is a blog post about integration with SonarQube.
I've also made a couple of tiny changes to the last post.
There are a couple of things that I am not 100% sure on.
Can you check that you are happy with this statement:
> Normally AppVeyor will not decrypt secure variables in Pull Requests, as in this case a Hacker could send you a PR and then read all of your secure data. However, for SonarQube to analyse Pull Requests, it is necessary. You need to decide whether you can live with this.
Can you also check that my method of creating an alternative pull request build is as you would recommend:
```yml
build_script:
- ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { blah }
- ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { other blah }
```
Thanks and Happy Christmas :) …

Add SonarQube integration blog post

---

src/docs/services-databases.md

SQL in MySQL is capitalized for directory path
some minor changes in PostgreSQL like 9.4 is the default and should be used for the example

SQL in MySQL is capitalized for directory path

---

src/docs/installed-software.md

**Note:** this is one of two pull-requests I'm submitting - both attempt to address the same problem, but each in a different way, so pick the one you prefer.
Specifically, the Qt 5.6 version stated at https://www.appveyor.com/docs/installed-software/#qt is out of date - it claims Qt 5.6.1, but the servers have 5.6.2 instead.
This pull request simply corrects the patch version number.
However, that page already omits the patch number for Qt version 5.3, 5.4 and 5.5.  So it might make better sense to instead simply drop the patch level version from the Qt 5.6 and 5.7 versions instead, which is what my other pull request (https://github.com/appveyor/website/pull/243) does instead.
Cheers.

Update Qt 5.6 version to reflect production

---

src/_posts/2017-03-17-codecov.md

Hi Feodor, the "Code Coverage" status image under Add Coverage Graphics to the Repository section was working for me when running it locally, so its hard for me to know whether this change will work or not.
However, it looks like an error, so hopefully this fix will do it.
Cheers
Cedd

Try to fix up example code coverage badge

---

src/docs/lang/cpp.md

Covers build configuration for Visual Studio.
Closes https://github.com/appveyor/ci/issues/1444

Add lang/cpp.md on building C/C++ projects

---

src/docs/build-environment.md

To be useful, the full manifest ID (or tag name, though tags can be moved) is required for people to actually reference. Resolves issue #295.

Add tags and manifest IDs for Windows images

---

src/docs/appveyor-yml.md

As per https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-nuget-cache, NuGet v3 has a different cache location.

Example of caching NuGet v3 location

---

src/docs/how-to/selenium-testing.md

Running `choco install firefox -version 46.0.1` results in a warning:
```
Parsing -version resulted in error (converted to warning):
Cannot bundle unregistered option '-e'.
```
According to [chocolatey docs](https://chocolatey.org/docs/commands-reference#how-to-pass-options-switches), the single dash is meant for one-character switches, which can be bundled. Hence `-version` is interpreted as 7 switches: `-v -e -r -s -i -o -n`. `--version` should be used instead.

selenium-testing.md: fix invalid option in example choco command

---

src/docs/lang/cpp.md

The PlatformToolset section is a feedback item based on experience when attempting to run an open source project under AppVeyor. This is one of the potential problems that AppVeyor users may encounter. Other issues may arise.

Add information on PlatformToolset and DefaultPlatformToolset

---

src/docs/services-databases.md

Confirmed via [dbatools](https://github.com/sqlcollaborative/dbatools) project that the sql2016 instance of SQL Server is Developer Edition and not Express.

Correct the edition of SQL Server 2016

---

src/docs/appveyor-yml.md

1. Added missed apostrophe
2. Removed duplicated "matrix:" block start
Now file is validated without errors.

fixed typo and duplicate key error

---

src/docs/api/team.md

- There is an exception returned from the Update User API method if these properties are not included:
```
"successfulDeploymentNotification": "all",
"failedDeploymentNotification": "all",
```

(doc) Added missing properties for User Requests

---

src/docs/build-configuration.md

Add section on scripts and interpreters. The page does not introduce them to the reader.
Add information on accessing variables in the two script engines. PowerShell is especially sneaky because it requires `$env:MY_VARIABLE`, and not `$MY_VARIABLE`. I wasted about 4 hours trying to figure out what was going wrong.

Update docs on scripts and interpreters

---

src/docs/build-environment.md

Apparently, LLVM/clang are available on the latest image:
```
> which clang
/c/Program Files/LLVM/bin/clang
> which clang++
/c/Program Files/LLVM/bin/clang++
> which clang-cl
/c/Program Files/LLVM/bin/clang-cl
> clang-cl -v
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```
------
Current docs show no green dot in VS2017 column
https://www.appveyor.com/docs/build-environment/#llvm

Mark LLVM as available on Visual Studio 2017

---

src/docs/lang/ruby.md

Having helped with AV testing here and there, there are many people that would like to test with AV, but are unfamiliar with Windows and Ruby builds for it.  Hence, I thought adding some info might be helpful.
There may be things that could be added or removed, so I'm happy to add (& squash) more commits if needed.  I'm not sure if I've set up the 'h' markdown correctly for the TOC.
Thanks again for AV OSS support...

Update to ruby.md with build (RI vs RI2) & openssl info

---

src/_posts/2016-11-22-create-signed-aligned-xamarin-apk.md
src/_posts/2016-12-23-sonarqube.md
src/_posts/2017-03-17-codecov.md

This now relies on Bash and Powershell, which exist on the AppVeyor machine image and will be present on virtually all developer machines. This should make it easier to replicate the build locally, as there is no need to install python or the codedov python package.

Amend CodeCov upload script 

---

src/docs/lang/cpp.md

Caching the installed folder allows for quicker rebuilds as packages don't need to be rebuilt when running vcpkg install.

Added section about caching vcpklg installed packages

---

src/docs/build-environment.md

Refer to ccbf2c87ad7a17f2979e3697cc787073543679ea.
The current version of docs is maping one path to two Minicondas:
>Miniconda2 4.3.27 (Python 2.7.13) - C:\Miniconda
Miniconda3 4.3.27 (Python 3.6.2): C:\Miniconda36 or C:\Miniconda
I haven't tested but assume from path of x64 version.

fixed Miniconda path

---

src/docs/build-environment.md

The worker images are no longer identical in their Boost availability, and this information was in the prose rather than the table.

Update Boost availability list

---

src/docs/build-configuration.md

Patching .csproj and .props/other similar doesn't support files with xmlns defined. Note may save some people a headache.
See https://github.com/appveyor/ci/issues/1750#issuecomment-356366858

Add note about csproj/props xmlns not supported

---

src/docs/how-to/filtering-commits.md

I couldn't decipher what the slashes (/) were for in the regex expression, but I remembered a note about this on Branches and Tags. Just copying the note from there to here.

Add regex 'slash note' to commit page

---

src/docs/notifications.md

As mentioned in https://github.com/appveyor/ci/issues/2165 I'm seeing a `commitMessageExtended` value in my deployment payloads. I haven't checked normal build payloads so this update might not be 100% accurate.
There's also `environment`, `build`, and `buildJob` sections missing but I'm not sure if they're part of all payloads so I've left that out for now.

Add commitMessageExtended to the webhook payload

---

src/docs/lang/cpp.md

May be good to wait for Vcpkg's clarification about [where to run vcpkg integrate install from](https://github.com/Microsoft/vcpkg/issues/3052).

Document vcpkg integration status

---

src/docs/branches.md

The previous text made it look like 'except' was a top-level keyword. It's not, at least not according to the appveyor.yml reference.

Clarify branches/except syntax

---

src/docs/getting-started-with-appveyor-for-linux.md

See [here](https://ci.appveyor.com/project/PowerShell/psscriptanalyzer/build/1.0.2405/job/hw222xh15xswspit) for a build that shows that PowerShell Core has already been updated to version 6.0.2.
I don't know why GitHub shows a diff for the localstack line, which I did not touch, that must be a bug in GitHub (I edited via the GitHub web UI)

Update PowerShell Core version available Ubuntu image from 6.0.1 to 6.0.2

---

src/docs/build-environment.md

Apparently, CMake on AppVeyor has been updated to the latest release earlier this week.

Update from CMake 3.10 to 3.11

---

src/docs/branches.md

Running this code fails with:
```
Error parsing appveyor.yml: 'for' must be a sequence. (Line: 7, Column: 3)
```
Fix is to add an `-` to make it a sequence.

Fixed bug in documentation example

---

src/docs/environment-variables.md

They were listed as `gitlab`/`github`, but in reality they are `gitLab`/`gitHub` (with an uppercase `L`/`H`) respectively.
Possibly `bitbucket` is also affected, but I haven't tested it.

environment-variables: fix APPVEYOR_REPO_PROVIDER value for GitLab and GitHub

---

src/assets/css/pages/installed-software.css

Before and after
This works fine under Opera 53 (stable) Firefox 66.0.2 Chrome  67 this gives better results multi-browser with variant resolutions from 1080p up to UHD 2560x1440p.
bare with me :)
Edit: There we go. updated PR I haven't updated gif but it works more or less the same in the 3 browsers, will do more testting in meanwhile, see if I can sideload these fixes in the MS's browsers.

build-environment.md: wrangle rotated text inside table fixes #485

---

src/docs/build-configuration.md

See: https://help.appveyor.com/discussions/questions/22249-docs-question
I updated the corresponding section to ensure the users have a clearer pictures when the appveyor.yml is supported and why it is not supported in certain scenarios.

Update section Classic Git repositories and YAML

---

src/docs/deployment/bintray.md

It's not an AWS key, it's a Bintray API key

Make Bintray documentation clearer

---

src/_posts/2014-03-25-continuous-delivery-of-windows-azure-cloud-services-with-appveyor-ci.md

as suggested here https://help.appveyor.com/discussions/problems/15494-azure-cloud-service-deployment-failure

fix outdated link to "Download Azure account publishing profile"

---

src/docs/appveyor-yml.md
src/docs/build-configuration.md

It seems logical that the test steps continue in the same directory
where the build left off, but this was not explicit. Even more
confusing, "build.project" is *not* affected by directory changes in
"before_build".
I am not sure when "before_package" is exactly executed, so it remains
undocumented in build-configuration.md.

Clarify order and behavior related to directory changes

---

src/docs/build-phase.md

The documentation says that if you need to customize the msbuild parameters, that you have you resort to `build_script:`. There is another option, a file in the root of the repo called `msbuild.rsp.` I document it here.
Reference: https://msdn.microsoft.com/en-us/library/ms404301.aspx

Noted the ability to use response files

---

src/docs/api/index.md

I attempted to use the example in my shell, but I could not paste it in. It was not valid. This change is simpler for scripting, hacking or experimenting

Updated Sample Powershell code to paste-able Powershell code

---

src/docs/how-to/rdp-to-build-worker.md

After I set `APPVEYOR_RDP_PASSWORD`, the RDP connection stopped working. From searching the help forum, I found the solution in this comment:
https://help.appveyor.com/discussions/problems/6666-rdp-password-issue#comment_42563423

Explain password requirements for configuring RDP

---

src/docs/build-environment.md

The number of build jobs was stated incorrectly in the section "Using multiple images for the same build," which describes the interaction between the build matrix and worker images.

Fix typo in section "Using multiple images for the same build"

---

src/docs/windows-images-software.md

My builds started failing yesterday due to `Current` installing v11 instead of v10 which is how I noticed this was installed now. I'm sure there's other changes that need to be made to this list but this is what I'm aware of so far.

Add node 11 to the list of installed versions

---

src/docs/appveyor-yml.md
src/docs/branches.md
src/docs/deployment/github.md
src/docs/deployment/index.md

Linux environment variables are case sensitive, and Windows is not,
so consistent upper casing ensures configurations will work on both.

Fix casing of APPVEYOR_REPO_TAG.

---

src/docs/how-to/private-git-sub-modules.md

This is a working example of creating a private ssh key for private git submodules on ubuntu image.
Note: The escaped new line in `ps` example is not needed in `sh` example because `echo` already puts new lines in.

Add example of for ubuntu image

---

src/docs/how-to/ssh-to-build-worker.md

Sometimes a worker terminates an ssh connection early even with `sh: export APPVEYOR_SSH_BLOCK=true` because the `enable-ssh.sh` script already ran.
I useful solution I came up with was to add `sh: sleep 60m`.  I can kill the `sleep` process from inside my ssh session. Or I can manually cancel the build from the web ui.

ssh-to-build-worker.md: Additional tip for ubuntu

---

src/docs/running-tests.md

Update links to msdn sources to point to docs.microsoft.com.
Without region/language or VS version preset.

Update links to docs.microsoft.com

---

src/docs/build-configuration.md

Adds a section describing the build mode and how to switch from "MSBuild" mode to "Script" mode.
Addresses https://help.appveyor.com/discussions/problems/12705-custom-build-script-script-mode.

build-configuration: add sction about controlling build mode

---

src/docs/branches.md

As commented in https://help.appveyor.com/discussions/problems/3483-github-tag-push-doesnt-trigger-build#comment_38384095
and recently tested in https://github.com/jneira/dhall-haskell/commit/f5d44d036b2d009beb2b0c0d6a4ef6a708f9d968

Add advise to allow trigger builds on tags when using branches:only:

---

src/_includes/docs_sidebar.html
src/docs/lang/python.md

This adds a new chapter to the documentation, which explains concisely how to setup up (best practice) testing automation on AppVeyor for projects using the Python programming language.

Add Python language chapter to docs

---

src/docs/windows-images-software.md

Noticed a minor oversight in the software table.
On the `Visual Studio 2019` image the curl version is also v7.55.1.
https://ci.appveyor.com/project/Farwaykorse/appveyorhelpers/build/job/1tuxie3p4y5vo34e#L20

curl 7.55.1 is installed on the VS 2019 image

---

src/docs/deployment/webhook.md

I just noticed this small typo in the documentation, most likely a copy-paste mistake. Thanks for your work on AppVeyor!

Fix request_timeout typo in webhook.md

---

src/docs/how-to/git-push.md

I have noticed that the extra newline that `Add-Content` adds to `.git-credentials` started making problems with git in the `Visual Studio 2019` image, probably because git changed in response to [CVE-2020-11008](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11008).

Add -NoNewline option to Add-Content

---

src/docs/api/index.md

Adding a link to the API token page, as requested: https://help.appveyor.com/discussions/questions/49620-where-is-the-api-token-page-under-the-appveyor-account

Adding a link to the API token page

---

src/docs/how-to/filtering-commits.md

AND and OR logic difference applies to the different files.
The matching rules always use OR logic.
It would be possible to mention this difference in the logic statement, but that results in even more text.
Using the same sentence and accentuation style seems to be clearer.
\+ added a few articles
\+ Removed the first example. It does not add anything. Contains unnecessary rules (1st covers 2nd). And increases the distance to the section explaining the rules format.

Replace confusing logic statement with consistent explanation

---

src/docs/windows-images-software.md

According to the actual image, `mingw810_32` is available under VS 2019 image, so I added it here.
ps. I'm not sure if it actually also available under other images, please double check if possible. And maybe consider also listing MinGW 64 path (e.g. `C:\Qt\Tools\mingw810_64`)?

Add MinGW 8.1.0 info for Qt

---

src/docs/deployment/web-deploy.md

The documentation said that the parameter and environment variable name has to be `DefaultConnection-Web.config Connection String`. This isn't necessarily the case. It has to be the name of your database connection + `-Web.config Connection String`.
So if you have this in your Web.config:
```
<connectionStrings>
<add name="MainDb" connectionString="..." providerName="System.Data.SqlClient" />
</connectionStrings>
```
Then you can use `MainDb-Web.config Connection String` as parameter name and environment variable name.

Allow connection name to be something other than DefaultConnection

---

src/_posts/2016-12-23-sonarqube.md

SonarQube potentially requires a specific version of Java, which might not be the default one on the build machine, [as reported on the companion repository](https://github.com/appveyor/website/issues/779#issuecomment-747202459)
This adds some instructions for fixing this problem, and fixes #779

Add Java version instructions to SonarQube post

---

src/docs/lang/cpp.md

This proposal adds in a section for msvs 2019, detailing the path to vsvars*.bat between 32bit and 64bit.
Recommended to accept due to the GUI and .yml accepting MSVS 2019.
I release any copyright to the maintainers of this repo to do whatever they wish.
Sorry about the branch name in advance, I used github to submit the minor changes.

Correct documentation to include msvs 2019

---

src/docs/how-to/private-git-sub-modules.md

ssh-kengen -t generates ssh format keys on windows:
``ssh
-----BEGIN OPENSSH PRIVATE KEY-----
keyss.....
-----END OPENSSH PRIVATE KEY-----
```
the powers shell script should change accordingly

change keys format if needed

---

src/docs/lang/python.md

Modernize https://www.appveyor.com/docs/lang/python/
The current example installs `tox` on Python 2 which died 672 days ago on 1/1/2020.
The proposed example [uses `py`](https://docs.python.org/3/using/windows.html#python-launcher-for-windows) to install `tox` on Python 3.

Testing with Python: Use `py` and add Python 3.8

---

src/docs/windows-images-software.md

in this Visual Studio 2022 image:
- I don't see JDK 14 to be available
- I don't see JDK 1.7.0 default in path 
- the path to JDK 17 is different then stated in the documentation
Remarks:
- I do see JDK 1.8.0 default in the path. Should there a new row for 1.8.0 indicating that it is in default path?

Update JDK versions in Visual Studio 2022 image

---

src/docs/linux-images-software.md

Its support ended on August 2021.

.NET Core 2.1 is EOL.

---

src/docs/how-to/repository-shallow-clone.md

It took me a while to figure out why git submodule update failed with shallow_clone. I also saw that [somebody else](https://help.appveyor.com/discussions/problems/27363-how-to-load-public-submodules-in-a-private-repo) had the same issue. I think this small addition will make it clearer.

State that git operations are not possible with shallow_clone

---

src/docs/lang/go.md

As far as I can tell, `stack` is not working as expected on Windows, this adjusts the documentation to some env var changes in order to get the desired go version.

Update Windows golang documentation

---

src/docs/windows-images-software.md

The information here currently is wrong in several ways.
I've updated based on checking the contents of c:\mingw-w64 in each image.

Correct mingw-w64 version information

---

src/docs/linux-images-software.md

I noticed the PG version is different on the image to the documentation, providing an update.

Update postgres version for ubuntu 20 image

---

src/docs/lang/python.md

Python 3.12 will also be production-ready in one month.

python.md: Add Python 3.11 to the docs

---

src/docs/lang/nodejs-iojs.md

Update to Windows image to Visual Studio 2022
Focus on testing Node.js v18 and 20.  Node.js v22.1.0 is available but is not yet installed on the AppVeyor Windows image to Visual Studio 2022.
https://github.com/nodejs/node/releases
https://nodejs.org/en/about/previous-releases
`io.js` is long gone so remove all mention of it.

Update Node.js instructions for current versions of Node.js.
