- NJekyll/Engine/Bundles.cs
- NJekyll/Engine/CollectionMetadata.cs
- NJekyll/Engine/ContentFile.cs
- NJekyll/Engine/ContentFormat.cs
- NJekyll/Engine/DataFolder.cs
- NJekyll/Engine/Filters.cs
- NJekyll/Engine/IncludesFolder.cs
- NJekyll/Engine/Layout.cs
- NJekyll/Engine/Page.cs
- NJekyll/Engine/Paginator.cs
- NJekyll/Engine/Routes.cs
- NJekyll/Engine/Site.cs
- NJekyll/Engine/Tags/Highlight.cs
- NJekyll/Global.asax.cs
- NJekyll/Properties/AssemblyInfo.cs
- NJekyll/Web.Debug.config
- NJekyll/Web.Release.config
- NJekyll/Web.config
Also, fix a couple /analyze issues along the way.
https://github.com/appveyor/website/pull/30/files?w=1
> Clean up NJekyll code with Codemaid.

- NJekyll/site/css/02-site/header.css
- NJekyll/site/css/03-pages/home.css
As usual IE is bugged as hell...
Fixes #40.
> Fix homepage CSS background images for IE.

- NJekyll/site/docs/deployment/index.md
> Spelling fix

- NJekyll/site/docs/how-to/skip-build.md
Guess a note about `[skip appveyor]` should be added
> added `[skip appveyor]` to the docs

- NJekyll/site/docs/deployment/github.md
see https://help.appveyor.com/discussions/problems/2975-github-deployment
> Add note about Github descriptions

- NJekyll/site/docs/deployment/agent.md
Updating Unattended Deployment Agent installation block to include the parameter for deployment group.
> Updating unattended deployment agent block

- NJekyll/site/docs/build-cache.md
Typo read 7xip instead of 7zip
> Correct a typo in build-cache.md

- NJekyll/site/docs/installed-software.md
added python 3.5 installation to docs as of appveyor/ci#428
> add python 3.5.0 installation

- NJekyll/site/docs/environment-variables.md
As per https://github.com/appveyor/ci/issues/522
> Added new environment variable to documentation

- NJekyll/site/docs/how-to/rdp-to-build-worker.md
Assuming that this should be 60 as mentioned elsewhere in the docs...?
> corrected max rdp time

- NJekyll/site/docs/deployment/environment.md
- NJekyll/site/docs/deployment/github.md
- NJekyll/site/docs/deployment/index.md
Providing information on where to go to create an environment
> Documentation Update: Environments

- NJekyll/site/docs/deployment/github.md
Just a quick note in case this catches anyone else that is new to AppVeyor (like me). Thanks for the awesome platform!
> add: note that github provider name is case sensitive.

- NJekyll/site/docs/deployment/github.md
- NJekyll/site/docs/packaging-artifacts.md
Here is a patch to document the force_update option, as well as a few minor grammatical updates.
> Document force_update for GitHub releases

- NJekyll/site/docs/deployment/azure-blob.md
> Add set_content_type to azure-blob documentation

- NJekyll/site/docs/appveyor-enterprise/index.md
- NJekyll/site/docs/deployment/web-deploy.md
- NJekyll/site/docs/how-to/filtering-commits.md
- NJekyll/site/docs/how-to/selenium-testing.md
- NJekyll/site/docs/lang/ruby.md
- NJekyll/site/docs/lang/xamarin.md
> Minor Typo

- NJekyll/site/docs/deployment/bintray.md
Replace "BinTray" by "Bintray" (reference: https://bintray.com)
> Typo Bintray

- NJekyll/site/docs/build-configuration.md
Project was migrated from Google Code to GitHub.
> Fix link to NCrontab project

- NJekyll/site/docs/build-worker-api.md
* Added description of options, from command-line help.
* Some of the options are required.
* `-Name` was missing from some of the example commands.
> Add required options for AddTest/UpdateTest

- Gruntfile.js
- src/404.html
- src/_layouts/default.html
- src/web.config
> Fix 404 error page

- src/web.config
> Add CSP header.

- src/_newsletters/2014-11-13-appveyor-premium-build-environment-and-new-pricing.md
- src/_posts/2014-11-13-appveyor-premium-build-environment-and-new-pricing.md
- src/docs/appveyor-enterprise/index.md
- src/docs/deployment/web-deploy.md
- src/docs/installed-software.md
- src/support.md
> Merge staging to master

- Gemfile.lock
- npm-shrinkwrap.json
> Update deps and gems.

- src/docs/installed-software.md
Fixes https://github.com/appveyor/ci/issues/1013
> Fix Firefox spelling

- src/docs/environment-variables.md
APPVEYOR_REPO_PROVIDER was missing `vso` & `gitlab` & values always lowercase in envvar.
> Add missing provider vso and gitlab

- src/_posts/2016-11-22-create-signed-aligned-xamarin-apk.md
Hi There
I have been exploring AppVeyor on a hobby project recently, and emailed Ilya Finkelshteyn to see whether a blog post on the subject would be welcome.
He sounded keen, so here it is!
I hope you like it.
Cheers
> Creating a Signed and ZipAligned APK (for Google Play) from Xamarin

- src/_posts/2016-11-07-aws-elastic-beanstalk.md
This is original YAML which works. For doc I put simplified flat PS commands which was not valid YAML.
> Fix wrong YAML sample

- Gemfile
- Gemfile.lock
- npm-shrinkwrap.json
> Update dependencies and gems.

- src/_includes/docs_sidebar.html
- src/eula.html
- src/privacy-policy.html
- src/terms-of-service.html
@XhmikosR can you tell me please why HTML check is complaining there: https://ci.appveyor.com/project/appveyor-website/website/build/1.0.941#L635?
> Updated ToS, EULA and privacy policy

- src/docs/build-phase.md
- src/docs/deployment/web-deploy.md
https://github.com/appveyor/ci/issues/1254
> Custom name for automatic WAP artifact doc

- Gruntfile.js
- src/assets/css/pages/installed-software.css
- src/assets/js/main.js
- src/docs/build-environment.md
> Build environment page tweaks

- src/docs/build-configuration.md
The section on AssemblyInfo patching didn't say what AssemblyInfo patching actually is. Feel free to suggest better wording.
> Describing what AssemblyInfo patching is.

- src/docs/build-environment.md
As seen here: https://ci.appveyor.com/project/tgjones/dotliquid/build/2.0.110#L136
I suppose it is the same for nunit2 but haven't checked.
> Fix nunit3 path

- src/docs/api/index.md
I'm using AppVeyor from a Mac to build Windows apps and packages.
Therefore I'm starting to use `curl` to automate some settings with your API.
So this might be helpful for others to use `curl`.
> Add example with curl

- src/docs/build-environment.md
Fixed highlighting markdown for MinGW PATH.
> fix bracket markdown

- src/docs/enterprise/setup-master-vm.md
https://github.com/appveyor/ci/issues/1697
> Clarifying dependency on path scripts

- src/docs/api/environments-deployments.md
To be consistent with other examples
> Corrected JSON Format

- src/docs/build-environment.md
https://github.com/appveyor/ci/issues/1693#issuecomment-322935108
> MSYS2 installed on VS2017

- src/docs/enterprise/creating-build-server-in-azure.md
- src/docs/enterprise/planning.md
Updated page with instructions for existing SSL certificate
> Updated instructions, and typos

- src/docs/lang/cpp.md
This PR is follow-up to the discussion and my comment in this thread https://github.com/appveyor/ci/issues/1410#issuecomment-328362246
> Add env configuration for Visual Studio 2017

- src/docs/lang/cpp.md
Add bare minimum about where to find the `vcpkg` and how to use it from appveyor.yml.
---
Complements appveyor/ci#1076
> Add basic section about VC++ Packaging Tool

- src/docs/build-environment.md
The image ID cannot be pulled so listing it isn't that useful. Please be sure to include tag and digest (the latter of which is immutable).
> Add useful tag and digest for docker images

- src/web.config
After this is merged to master and goes live, I'll submit the domain to https://hstspreload.org/.
> Switch to includeSubdomains and preload for HSTS.

- src/docs/build-configuration.md
https://github.com/appveyor/ci/issues/1772
https://github.com/appveyor/ci/issues/1750
> Document patching improvements

- src/docs/build-phase.md
https://github.com/appveyor/ci/issues/1759
> Excluding .NET Core projects from NuGet packaging

- src/web.config
> Remove report-uri

- src/docs/how-to/filtering-commits.md
https://github.com/appveyor/ci/issues/1865#issuecomment-344026974
> Better wording about skip commit string location

- src/docs/deployment/index.md
https://github.com/appveyor/website/issues/401
> Branch unavailable only for annotated tag

- src/docs/notifications.md
https://github.com/appveyor/ci/issues/1646
> Permalink in webhook body

- src/docs/deployment/azure-cloud-service.md
- src/docs/environment-variables.md
https://github.com/appveyor/ci/issues/1989
> Appveyor acs deployment upgrade mode

- src/_includes/docs_sidebar.html
- src/docs/deployment/azure-app-service-zip-pus-deploy.md
- src/docs/deployment/azure-app-service-zip-push-deploy.md
- src/docs/deployment/index.md
https://github.com/appveyor/ci/issues/1877
> Azure App Service Zip Push Deploy

- src/docs/notifications.md
> {{build.commitAuthor}} does not display correctly

- src/docs/environment-variables.md
I went looking for this, so figured I'd save the next person the trouble. :)
> Add format note to commit timestamp environment variable description.

- src/docs/how-to/rdp-to-build-worker.md
per https://help.appveyor.com/discussions/problems/6666-rdp-password-issue
> RDP password: provided clarification about yaml vs UI

- src/docs/lang/nodejs-iojs.md
Not sure if this is the right spot for this, but I wanted to add something about the error I was getting. The explanation for this came from https://github.com/appveyor/ci/issues/2283.
> Add a note about unexpected npm errors when using powershell to execute the script

- src/docs/build-environment.md
Perhaps the link to MS visual studio release rhythm article is unnecessary (could be short lived link too)?
Also, maybe a quick explanation of 'previous' images should be given here too for completeness?
> add reference to/explanation of visual studio preview image

- src/docs/build-phase.md
Sample XML following instructions for `IsPackable=false` showed a `true` value.
> Minor typo in build-phase.md

- src/docs/how-to/rdp-to-build-worker.md
- src/docs/how-to/ssh-to-build-worker.md
Follow-up to issue appveyor/ci#2124.
--
Please, double-check that this is correct and suits you.
> Improve/Sync' most of rdp-to-build-worker.md and ssh-to-build-worker.md

- src/_posts/2018-04-25-specialized-build-matrix-configuration-in-appveyor.md
Reported on https://github.com/appveyor/ci/issues/2380.
> 2018-04-25-*.md: Fix a copypasta wrt 'image: Ubuntu'

- src/docs/deployment/index.md
https://github.com/appveyor/ci/issues/2410#issuecomment-395218450
> Correct casing for Linux

- src/docs/environment-variables.md
Follow up to https://github.com/appveyor/website/pull/480
> All repo providers

- src/docs/deployment/agent.md
https://github.com/appveyor/ci/issues/2349
> Update deployment agent and document 'skip_acl'

- src/docs/getting-started-with-appveyor-for-linux.md
changed cass-sensitive to case-sensitive
> Fixed Typo

- src/docs/build-configuration.md
See https://help.appveyor.com/discussions/problems/16519-failure-in-ps1-script-results-in-successful-build
/cc @OwenMcDonnell
> added note about non-terminating errors in PS scripts

- src/docs/lang/cpp.md
https://github.com/appveyor/ci/issues/2733
> Address https://github.com/appveyor/ci/issues/2733

- src/docs/api/samples/download-artifacts-advanced-ps.md
Feature: Make Token Optional for public projects
Feature: Allow filtering to a specific branch
Feature: Allow Filtering to a specific Job Name (for instances where multiple compilations are run E.G. Windows and Linux)
> Powershell Advanced API Example: Add additional Functionality

- src/_updates/2019-01-16.md
- src/docs/linux-images-software.md
This images update mainly fixes LANG variable issue
https://help.appveyor.com/discussions/problems/18853-problem-with-powershell-core-611-in-ubuntu-and-ubuntu1804-images
> Update Ubuntu images 2019-01-16

- package-lock.json
- src/_posts/2016-12-23-sonarqube.md
Hi there
I wrote this article a couple of years ago and things have moved on, so the instructions don't work any more.
I've updated them to make sense with the way things are now.
I can either update the original article (which is what this pull request does) or create a new one if you prefer.
Cheers
Cedd
> Update Sonar Qube Blog post for 2019

- src/docs/build-phase.md
https://github.com/appveyor/ci/issues/2753
> Snupkg packaging (merge after feature deployment)

- src/docs/build-environment.md
- src/docs/windows-images-software.md
Addendum to 178a5a8e11588e773f960a26351edb23e5983c95.
> List Visual Studio 2019 image explicitly

- src/docs/build-phase.md
Noticed the instances of "paramater" while browsing the docs and figured I'd try to improve the syntax and spelling a bit; no changes to meaning or what is being said.
> a few spelling and grammar fixes

- src/docs/server/index.md
Based on what is available for Mac, this seems like a good fit.
> Add Chocolatey Installation instructions

- src/docs/build-environment.md
> build-environment.md: Add optional spaces to 'image:' list

- src/_posts/2018-09-11-how-to-skip-build-matrix-jobs-conditionally.md
- src/docs/build-configuration.md
- src/docs/getting-started-with-appveyor-for-linux.md
Easier to understand.
Addendum to 2aa3df785ba07ac08700c902467d03f4fc205b45.
> Add optional spaces to 'image:' list

- src/_posts/2018-09-11-how-to-skip-build-matrix-jobs-conditionally.md
- src/_posts/2018-09-18-ubuntu-1804-bionic-beaver.md
- src/_updates/2018-06-08.md
- src/docs/build-environment.md
- src/docs/getting-started-with-appveyor-for-linux.md
- src/docs/how-to/private-git-sub-modules.md
> Capitalize 'ubuntu' everywhere (it is not yet)

- src/docs/build-environment.md
Related to appveyor/ci#3125 and appveyor/ci#3111.
> build-environment.md: Update 'Visual Studio Preview images'

- src/docs/build-environment.md
> build-environment.md: Update 'Visual Studio Preview image'

- src/docs/windows-images-software.md
Related to appveyor/ci/issues/3377.
> windows-images-software.md: Fix Strawberry Perl version and path

- src/docs/windows-images-software.md
Here is an update to add the path for the NDK r16b in the server software list.
> Updating the NDK path for r16b

- src/docs/deployment/nuget.md
It might also be a good idea to explicitly describe what is meant by "artifacts of type **NuGet package**", when no artifact filter is specified.
> Include a regex which doesn't exclude snupkg files

- src/docs/how-to/git-push.md
Prior commit #9792bc3 failed to update all occurrences.
> Really add -NoNewline option to Add-Content

- src/docs/running-tests.md
Update for running test scripts with multiple examples
Custom test_script: echo, cmd, dotnet
> Update running-tests document

- src/docs/api/index.md
- src/docs/api/samples/download-artifacts-sh.md
converted and extended version of download-artifacts-advanced-ps.md
after searching for that too long... here it is, script is contributed under MIT
> docs: new sample download-artifacts.sh
